name: Deploy Frontend to S3   ## 워크플로우 이름

on:
  push:
    branches:
      - main    ## 1) main branch에 푸시될 때, 워크플로우 실행
    pull_request:
      branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-lates    ## Github에서 제공하는 최신 Ubuntu 환경 사용

    ## OIDC 인증을 위해 반드시 필요한 권한
    permissions:
      id-token: write   ## JWT(JSON Web Token) 발급 권한
      contents: read    ## 저장소 코드를 읽는 권한

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js   ## Node.js 환경 설정
        uses: actions/setup-node@v4
        with:
          node-version: '22'  ## 2) 프로젝트의 Node.js 버전에 맞게 수정
          cache: 'npm'        ## npm 의존성 캐싱으로 빌드 속도 향상

      - name: Install dependencies
        run: npm install      ## 3) 프로젝트에 맞는 의존성 설치 명령어

      - name: Build project
        run: npm run build    ## 4) 프로젝트의 빌드 명령어

      - name: Configure AWS Credentials  ## OIDC 인증을 통해 AWS 임시 자격 증명 획득
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::393099937963:user/github-actions-frontend-user
          aws-region: ap-northeast-2   ## 6) S3 버킷이 위치한 AWS 리전

      - name: Deploy to S3
        run: |
          aws s3 sync ./build/ s3://second-subtitle-app-frontend --delete 
          

